[project]
name = "common-venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "jupyter>=1.1.1",
    "kafka-python>=2.3.0",
    "mrjob>=0.7.4",
    "notebook>=7.4.7",
    "pyspark>=4.1.0",
]
